package com.thelads.core.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CrosshairDesignTest {
    private final CrosshairDesign.Rules defaults=new CrosshairDesign.Rules(false,false,false,true,false,true,false,true,true);
    private CrosshairDesign.Visibility state(boolean third,boolean spectator,boolean target,boolean hidden,boolean debug,boolean container,boolean scope,boolean ranged,boolean throwable){return new CrosshairDesign.Visibility(third,spectator,target,hidden,debug,container,scope,ranged,throwable);}
    @Test void vanillaEligibilityRemainsDefault(){assertTrue(CrosshairDesign.visible(state(false,false,false,false,false,false,false,false,false),defaults));assertFalse(CrosshairDesign.visible(state(true,false,false,false,false,false,false,false,false),defaults));assertFalse(CrosshairDesign.visible(state(false,true,false,false,false,false,false,false,false),defaults));assertTrue(CrosshairDesign.visible(state(false,true,true,false,false,false,false,false,false),defaults));assertFalse(CrosshairDesign.visible(state(false,false,false,true,false,false,false,false,false),defaults));}
    @Test void scopeOverridesOrdinaryVisibility(){assertFalse(CrosshairDesign.visible(state(false,false,false,false,false,false,true,true,false),defaults));}
    @Test void contextGuardsApplyIndependently(){var rules=new CrosshairDesign.Rules(true,true,true,false,true,true,false,true,false);assertTrue(CrosshairDesign.visible(state(true,true,false,true,false,false,false,true,false),rules));assertTrue(CrosshairDesign.visible(state(false,false,false,false,false,false,false,false,false),rules));assertFalse(CrosshairDesign.visible(state(false,false,false,false,false,true,false,true,false),rules));assertFalse(CrosshairDesign.visible(state(false,false,false,false,true,false,false,true,false),rules));assertFalse(CrosshairDesign.visible(state(false,false,false,false,false,false,false,true,true),rules));}
    @Test void attackAndBowGapsRespondAndClamp(){assertEquals(2,CrosshairDesign.gap(2,true,1,true,1));assertEquals(20,CrosshairDesign.gap(2,true,0,true,0));assertEquals(2,CrosshairDesign.gap(2,false,0,true,-1));assertEquals(2,CrosshairDesign.gap(2,true,100,false,0));}
    @Test void opacityMultipliesExistingAlpha(){assertEquals(0x40abcdef,CrosshairDesign.alpha(0x80abcdef,.5));assertEquals(0x00ffffff,CrosshairDesign.alpha(0xffffffff,Double.NaN));assertEquals(0x80808080,CrosshairDesign.tint(0xffffffff,.5,true));assertEquals(0x80ffffff,CrosshairDesign.tint(0xffffffff,.5,false));}
    @Test void shapeDimensionsRemainIndependent(){var shape=CrosshairDesign.geometry(0,9,3,2,2);assertEquals(-11,shape.getFirst().left());assertEquals(-5,shape.get(2).top());assertTrue(CrosshairDesign.geometry(4,8,4,0,1).stream().anyMatch(r->r.left()>=7));assertTrue(CrosshairDesign.geometry(4,8,4,0,1).stream().noneMatch(r->r.top()>4));}
    @Test void everyGeometricStyleHasPositiveBoundedArea(){for(int shape:new int[]{0,1,2,4,5,6}){var parts=CrosshairDesign.geometry(shape,64,64,64,10);assertFalse(parts.isEmpty());assertTrue(parts.size()<66049);for(var r:parts){assertTrue(r.right()>r.left());assertTrue(r.bottom()>r.top());}}}
    @Test void drawingPersistenceIsBoundedAndExact(){var drawing=CrosshairDrawing.fromRows(999,999,java.util.List.of("#.#",".#."));assertEquals(64,drawing.width());assertTrue(drawing.get(2,0));assertFalse(drawing.get(100,100));var restored=CrosshairDrawing.fromRows(64,64,drawing.rows());assertEquals(drawing.rows(),restored.rows());}
    @Test void drawingCopiesAndResizesPreserveCenter(){var original=new CrosshairDrawing(9,9);original.set(4,4,true);var resized=original.resized(17,17);assertTrue(resized.get(8,8));var copy=original.copy();copy.set(4,4,false);assertTrue(original.get(4,4));assertFalse(copy.get(4,4));}
    @Test void drawingRowsMergeContiguousPixelsOnly(){var drawing=CrosshairDrawing.fromRows(5,3,java.util.List.of("##.##",".....","..#.."));var rectangles=drawing.rectangles();assertEquals(3,rectangles.size());assertEquals(2,rectangles.getFirst().right()-rectangles.getFirst().left());}
}
