name = "The Lads Client"
author = "ArashYT"
version = "BETA-0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69e01c3d623ae17e1a9925076455aaa8a333b5e34d3eddc9f038c67532aa7e22"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
