name = "The Lads Client"
author = "ArashYT"
version = "BETA-0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d65fcea99531580cef778603091f664cbd0b8ecd23d1f92ef43238b63e70f97b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
