name = "The Lads Client"
author = "ArashYT"
version = "BETA-0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36dca33defe43015240192aa102da9bfd200b3adff9ca3e0897b18657f8ce5f1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
