# Kill banner accent colour per variant (tools/killbanner/gen_accents.py)
aemondir=FFB63A,FFFFFF,3A7CFF,6C00FF
aeris=4769FF,FF5F37,FF559F,DE06FF
araxys=21DEFF,EB00FF,FF0A08,FFFFFF
araxysep9=21DEFF,EB00FF,FF0A08,FFFFFF
arcanecollectorsset=10C1FF
ayakashi=FF0009,FFFFFF,FFFFFF,4C79FF
blackspyre=FFBB5D,4031FF,FF0001,FFFFFF
blackthorn=FF0027,FF9F3C,22FFCA,7752FF
blastx=FF00CA
bolt=5AACFF,FF1611,FFFFFF,FFFFFF
bubblegumdeathwish=FF19E0
bubblegumdeathwish2=FF8B2B
bubblegumdeathwish3=FF0E05
bubblegumdeathwish4=77FF1D
champions2021=FFD677
champions2022=FFD677
champions2023=FFD677
champions2024=FFB471
champions2025=FF3921
chronovoid=1C44FF,7900FF,FF0D81,FFA300
cryostasis=1AADFF
cyrax=FFFFFF,FF2D2C,FF8915,D02CFF
default=2BFFB3,2BFFB3
divergence=FFD76D,FF64F5,7473FF,D8FF4F
dolmirsrevenge=FFFFFF,FFFFFF,AAFF76,30C9FF
doombringer=FF8A00,02FF8B,0092FF,50FF2E
elderflame=FFBB00
evoridreamwings=7710FF,54FF4A,FF1D99,FF6702
exo=A300FF,FF8700,FF0214,FF7BE5
forsaken=00FF63
gaiasvengeance=FF6269
gaiasvengeanceep7=FF6269,26BBFF,49FF64,FF6800
glitchpop=AF63FF
glitchpop20=AF63FF
helix=A1FF00,FF1E0A,CE12FF,61A0FF
holomeridian=0BA9FF,FFBB20,FF221F,29FF60
imperium=36FFDA,FF0812,FFFFFF,838DFF
ion=1D74FF
ionep5=1D74FF,0AFFAA,FF2A5E,FFFFFF
kuronami=44BAFF,614CFF,FFFFFF,FF314C
magepunk=1BA9FF
magepunkep3=1BA9FF
magepunkep6=1BA9FF,2FFF5D,FF3700,FFD22B
mystbloom=FF459E,7A8AFF,FF6542,7668FF
mystbloom-v25=FF459E,7A8AFF,FF6542,7668FF
neofrontier=1FFF21,E163FF,59FFCB,FFED00
neptune=FFB829
neptunev25=FFB829
nocturnum=FF0444,FFFFFF,1DA9FF,5E00FF
oni=4FFF5E
oniep6=4FFF5E
orabyonetap-ignition=FF162F
orabyonetap-lawyer=FFAD7D
orabyonetap-raja=439CFF
orabyonetap-renegade=8F64FF
orabyonetap-watch=8DFF16
origin=04FF6A
overdrive=FFAE1D,00A2FF,FF37FC,FF4635
phaseguard=FF7E2B,4BA8FF,4CFF2E,FFE227
preludetochaos=FF04FC
preludetochaosv25=FF04FC,FF5F38,00FF02,006DFF
prime=5C69FF
prime20=0012FF
primordium=FF4929,49FF8F,26B8FF,FFC657
protocol781-a=FF1000
radiantcrisis001=E1FF93
reaverep5=9200FF
reaverv26=9200FF,FF0000,FF0D1B,50FFB1
recon=00DDFF
res-bazookabadger=1396FF
res-dancefever=8637FF
res-knockout=FF9200
rgx11zpro=B8FF04
rgx11zproep4=B8FF04
rgx11zproep9=B8FF04,FF0410,04AEFF,FF9604
ruination=32FFE1
sentinelsoflight=FFDA56
sentinelsoflightep7=FFDA56,FF7DD4,ADFF95,7672FF
singularity=9300FF
singularityep9=9300FF,FF6B1B,FFD931,67A6FF
solarstride=FF7548,4E11FF,61A8FF,FF1A51
sovereign=4EC7FF,75FFBA,FF1514,8A52FF
sovereignep8=4EC7FF,75FFBA,60FFEC,FF3078
spectrum=FF0000
splashx=FF6217,5EE1FF,5AFF2C,CF09FF
valianthero=FFE500,FF7814,C169FF,0695FF
vct=FFFFFF
vct2025=FFFFFF
xerofang=FF3939,4A49FF,FF00FF,36FFFC
