plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'
    api 'com.google.code.gson:gson:2.11.0'
    api 'org.slf4j:slf4j-api:2.0.16'
    api 'club.minnced:java-discord-rpc:2.0.1'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
